// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /api/business-leads/:business/:id/quick-toggle
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function PATCH(request) {
  return dispatch("PATCH", "/api/business-leads/:business/:id/quick-toggle", request);
}
