// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /api/clients/:clientId/contributors
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function GET(request) {
  return dispatch("GET", "/api/clients/:clientId/contributors", request);
}

export function POST(request) {
  return dispatch("POST", "/api/clients/:clientId/contributors", request);
}
