// Auto-report chart kit — the React version of arKpiCard / arBars /
// arStackedBars / arDonut / arFunnelChart / arHighlightTable / arLegend.
//
// SHARED ON PURPOSE. /clients/:id (staff) and /client-view/:token (customer)
// render the same report from the same data. Keeping one kit is what stops the
// customer-facing copy from quietly diverging from the internal one; the
// original achieved that by having both pages call the same HTML builders, and
// this preserves it as components.
//
// Styling lives in app/globals.css, generated by scripts/gen-css.mjs from
// buildAutoReportCss() — the same CLIENT_REPORT_STYLES constant the legacy
// server-rendered pages use. These are deliberately GLOBAL class names, not CSS
// modules: two pages and a generator share them.
//
// Server components — no interactivity anywhere in the kit. The donut is inline
// SVG rather than a chart library, exactly as before.

import { ICONS } from "./icons";

export function ArIcon({ name }) {
  const path = ICONS[name];
  if (!path) return null;
  return (
    <svg
      viewBox="0 0 18 18"
      fill="none"
      stroke="currentColor"
      strokeWidth="1.5"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
      dangerouslySetInnerHTML={{ __html: path }}
    />
  );
}

export function ArKpiCard({ label, value, sub = "", color = "#8b7cf6", icon }) {
  return (
    <div className="ar-kpi" style={{ "--c": color }}>
      <div className="ar-kpi-top">
        <span className="ar-kpi-ico">
          {icon ? <ArIcon name={icon} /> : null}
        </span>
        <span className="ar-kpi-label">{label}</span>
      </div>
      <div className="ar-kpi-value">{String(value)}</div>
      {sub ? <div className="ar-kpi-sub">{sub}</div> : null}
    </div>
  );
}

export function ArKpis({ children }) {
  return <div className="ar-kpis">{children}</div>;
}

export function ArLegend({ items }) {
  return (
    <div className="ar-legend">
      {items.map((it) => (
        <span
          className="ar-legend-item"
          style={{ "--c": it.color }}
          key={it.label}
        >
          <span className="ar-dot" />
          {it.label}
          {it.value !== undefined && it.value !== null ? (
            <>
              {" "}
              <b>{String(it.value)}</b>
            </>
          ) : null}
        </span>
      ))}
    </div>
  );
}

export function ArEmpty({ children }) {
  return <div className="ar-empty">{children}</div>;
}

// Horizontal bars. Widths scale to the largest value in the set, so the leader
// fills the track. A non-zero value never renders thinner than 3% — otherwise a
// small count against a large max becomes an invisible sliver that reads as no
// data at all.
export function ArBars({
  rows,
  color = "#8b7cf6",
  emptyLabel = "No data yet.",
  hideZero = false,
}) {
  const visible = hideZero ? rows.filter((r) => Number(r.value) > 0) : rows;
  if (!visible.some((r) => Number(r.value) > 0)) {
    return <ArEmpty>{emptyLabel}</ArEmpty>;
  }

  const max = Math.max(1, ...visible.map((r) => Number(r.value) || 0));

  return (
    <div className="ar-bars">
      {visible.map((r) => {
        const v = Number(r.value) || 0;
        const pct = v > 0 ? Math.max(Math.round((v / max) * 100), 3) : 0;
        return (
          <div className="ar-bar-row" key={r.label}>
            <div className="ar-bar-label" title={r.label}>
              {r.label}
            </div>
            <div className="ar-bar-track">
              <div
                className="ar-bar-fill"
                style={{ width: `${pct}%`, "--c": r.color || color }}
              />
            </div>
            <div className="ar-bar-val">{String(v)}</div>
          </div>
        );
      })}
    </div>
  );
}

// One row per member, each split into segments by metric. Segments are sized
// with flex-grow (their share of that row) while the row itself scales to the
// busiest member — so both the mix and the volume read at once.
export function ArStackedBars({ rows, series, emptyLabel = "No data yet." }) {
  const totalOf = (r) =>
    series.reduce((s, m) => s + (Number(r[m.key]) || 0), 0);

  if (!rows.length || rows.every((r) => totalOf(r) === 0)) {
    return <ArEmpty>{emptyLabel}</ArEmpty>;
  }

  const maxTotal = Math.max(1, ...rows.map(totalOf));

  return (
    <div className="ar-bars">
      {rows.map((r) => {
        const t = totalOf(r);
        const widthPct =
          t > 0 ? Math.max(Math.round((t / maxTotal) * 100), 3) : 0;
        return (
          <div className="ar-bar-row" key={r.name}>
            <div className="ar-bar-label" title={r.name}>
              {r.name}
            </div>
            <div className="ar-bar-track">
              <div className="ar-stack" style={{ width: `${widthPct}%` }}>
                {series
                  .filter((m) => Number(r[m.key]) > 0)
                  .map((m) => (
                    <span
                      className="ar-seg"
                      key={m.key}
                      style={{ flex: Number(r[m.key]), "--c": m.color }}
                      title={`${m.label}: ${Number(r[m.key])}`}
                    />
                  ))}
              </div>
            </div>
            <div className="ar-bar-val">{t}</div>
          </div>
        );
      })}
    </div>
  );
}

// SVG donut. Each segment is a full-circle stroke clipped to its arc by
// stroke-dasharray and pushed into place with a negative dashoffset — the
// offset accumulates as segments are laid down, which is why this is a plain
// loop and not a map over independent values.
export function ArDonut({
  segments,
  size = 176,
  thickness = 24,
  centerNum = "",
  centerSub = "",
}) {
  const total = segments.reduce((s, x) => s + (Number(x.value) || 0), 0);
  const r = (size - thickness) / 2;
  const c = size / 2;
  const circ = 2 * Math.PI * r;

  const arcs = [];
  if (total > 0) {
    let offset = 0;
    for (const s of segments.filter((s) => Number(s.value) > 0)) {
      const len = (Number(s.value) / total) * circ;
      arcs.push(
        <circle
          key={s.label ?? s.color}
          cx={c}
          cy={c}
          r={r}
          fill="none"
          stroke={s.color}
          strokeWidth={thickness}
          strokeDasharray={`${len.toFixed(2)} ${(circ - len).toFixed(2)}`}
          strokeDashoffset={(-offset).toFixed(2)}
        />,
      );
      offset += len;
    }
  }

  return (
    <div className="ar-donut-wrap">
      <svg
        className="ar-donut"
        viewBox={`0 0 ${size} ${size}`}
        role="img"
        aria-label="Activity mix"
      >
        {/* Rotated so the first segment starts at twelve o'clock. */}
        <g transform={`rotate(-90 ${c} ${c})`}>
          <circle
            cx={c}
            cy={c}
            r={r}
            fill="none"
            stroke="rgba(255,255,255,0.07)"
            strokeWidth={thickness}
          />
          {arcs}
        </g>
        <text
          x={c}
          y={c - 1}
          textAnchor="middle"
          className="ar-donut-num"
          fill="var(--text-strong,#fff)"
        >
          {String(centerNum)}
        </text>
        <text
          x={c}
          y={c + 17}
          textAnchor="middle"
          className="ar-donut-sub"
          fill="var(--muted,#c4cce0)"
        >
          {String(centerSub)}
        </text>
      </svg>
    </div>
  );
}

// Centre-anchored funnel. Positive stages shade violet -> green with depth, so
// progress reads as movement toward green; dead-end stages are grouped below a
// divider in red. Width scales to the fullest stage, and the percentage is a
// share of the whole pipeline, not of the stage above.
export function ArFunnelChart({ stages, total }) {
  if (!total) return <ArEmpty>No leads in the pipeline yet.</ArEmpty>;

  const max = Math.max(1, ...stages.map((s) => Number(s.value) || 0));
  const positives = stages.filter((s) => !s.negative);
  const negatives = stages.filter((s) => s.negative);
  const posSpan = Math.max(1, positives.length - 1);

  const Row = ({ stage, index, span, isNeg }) => {
    const v = Number(stage.value) || 0;
    // An empty stage keeps a 2% stub so the funnel's shape stays legible.
    const pct = v > 0 ? Math.max(Math.round((v / max) * 100), 3) : 2;
    const share = total ? Math.round((v / total) * 100) : 0;
    const hue = isNeg
      ? 353
      : Math.round(262 - 112 * (span > 1 ? index / span : 0));
    const color = `hsl(${hue} ${isNeg ? 74 : 66}% 61%)`;

    return (
      <div className="ar-funnel-row">
        <div className="ar-funnel-label" title={stage.label}>
          {stage.label}
        </div>
        <div className="ar-funnel-bar-wrap">
          <div
            className="ar-funnel-bar"
            style={{ width: `${pct}%`, background: color }}
          >
            {v > 0 ? <span>{v}</span> : null}
          </div>
        </div>
        <div className="ar-funnel-meta">
          {v}
          <small> · {share}%</small>
        </div>
      </div>
    );
  };

  return (
    <div className="ar-funnel">
      {positives.map((s, i) => (
        <Row key={s.label} stage={s} index={i} span={posSpan} isNeg={false} />
      ))}
      {negatives.length ? (
        <>
          <div className="ar-funnel-divider">
            <span>Closed · negative</span>
          </div>
          {negatives.map((s) => (
            <Row key={s.label} stage={s} index={0} span={1} isNeg />
          ))}
        </>
      ) : null}
    </div>
  );
}

// Crosstab where every numeric cell carries a data bar scaled to ITS OWN COLUMN
// max, not the table max — columns measure different things (calls vs emails vs
// meetings) and a shared scale would flatten the smaller ones to nothing.
export function ArHighlightTable({
  columns,
  rows,
  totals,
  emptyLabel = "No data yet.",
}) {
  const numCols = columns.filter((c) => !c.isLabel);
  const max = {};
  for (const c of numCols) {
    max[c.key] = Math.max(1, ...rows.map((r) => Number(r[c.key]) || 0));
  }

  const fmt = (c, v) => (c.fmt ? c.fmt(v) : String(v));

  return (
    <div className="ar-table-wrap">
      <table className="ar-table">
        <thead>
          <tr>
            {columns.map((c) => (
              <th
                className={c.isLabel ? "ar-th-label" : "ar-th-num"}
                key={c.key}
              >
                {c.label}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.length ? (
            rows.map((r, i) => (
              <tr key={r[columns[0].key] ?? i}>
                {columns.map((c) => {
                  if (c.isLabel) {
                    return (
                      <td className="ar-td-label" key={c.key}>
                        {String(r[c.key] ?? "")}
                      </td>
                    );
                  }
                  const v = Number(r[c.key]) || 0;
                  const pct =
                    v > 0 ? Math.max(Math.round((v / max[c.key]) * 100), 5) : 0;
                  return (
                    <td className="ar-td-num" key={c.key}>
                      <span className="ar-cell-num">{fmt(c, v)}</span>
                      <span className="ar-cell-track">
                        <span
                          className="ar-cell-bar"
                          style={{ width: `${pct}%`, "--c": c.color }}
                        />
                      </span>
                    </td>
                  );
                })}
              </tr>
            ))
          ) : (
            <tr>
              <td colSpan={columns.length} className="ar-empty-cell">
                {emptyLabel}
              </td>
            </tr>
          )}
        </tbody>
        {rows.length && totals ? (
          <tfoot>
            <tr className="ar-total-row">
              {columns.map((c, i) =>
                i === 0 ? (
                  <td className="ar-td-label" key={c.key}>
                    Total
                  </td>
                ) : (
                  <td className="ar-td-num" key={c.key}>
                    <span className="ar-cell-num">
                      {fmt(c, Number(totals[c.key]) || 0)}
                    </span>
                  </td>
                ),
              )}
            </tr>
          </tfoot>
        ) : null}
      </table>
    </div>
  );
}

// Card shell used by every report section.
export function ArCard({ title, sub, children }) {
  return (
    <div className="ar-card">
      <div className="ar-card-head">
        <span className="ar-card-title">{title}</span>
        {sub ? <span className="ar-card-sub">{sub}</span> : null}
      </div>
      {children}
    </div>
  );
}
