// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /api/clients/:clientId/updates/:updateId
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function PUT(request) {
  return dispatch("PUT", "/api/clients/:clientId/updates/:updateId", request);
}
