// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /api/client-work-items/:id
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function GET(request) {
  return dispatch("GET", "/api/client-work-items/:id", request);
}

export function PATCH(request) {
  return dispatch("PATCH", "/api/client-work-items/:id", request);
}
