// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /api/business-leads/:business/:id
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function GET(request) {
  return dispatch("GET", "/api/business-leads/:business/:id", request);
}

export function PUT(request) {
  return dispatch("PUT", "/api/business-leads/:business/:id", request);
}

export function DELETE(request) {
  return dispatch("DELETE", "/api/business-leads/:business/:id", request);
}
