// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /login
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function GET(request) {
  return dispatch("GET", "/login", request);
}

export function POST(request) {
  return dispatch("POST", "/login", request);
}
