// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /api/clients/:id/leads
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function POST(request) {
  return dispatch("POST", "/api/clients/:id/leads", request);
}
