// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /api/clients/:id/blockers/:blockerId
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function PATCH(request) {
  return dispatch("PATCH", "/api/clients/:id/blockers/:blockerId", request);
}
