// Generates the JSON API route tree (app/api/**/route.js) from the Express
// route registry in lib/server/app.js. Each generated file is a thin wrapper
// that forwards to the original handler chain via dispatch(), so the files
// can never drift from the real routes.
//
// Page routes are NOT generated: each one is a hand-written
// app/<route>/page.jsx, and Next cannot host a page.jsx and a route.js at the
// same path.
//
// Run with:  node scripts/gen-routes.mjs

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { app } from "../lib/server/app.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const APP_DIR = path.join(ROOT, "app");

// NOTE: the byFolder grouping below is built after nextSegments() is defined,
// because folder names depend on dynamic-slug normalization.

// Next.js requires a single consistent slug name for a given dynamic position.
// Express uses per-route names (:id, :business, :leadId ...). Behavior here does
// not depend on the Next slug name (params are extracted by matching the original
// Express pattern at request time), so we normalize the slug name per tree
// position: the first dynamic param seen at a position fixes the folder name.
const dynamicAt = new Map(); // parentKey -> chosen slug name

function nextSegments(routePath) {
  const segs = routePath.split("/").filter((s) => s.length > 0);
  const out = [];
  let parentKey = "";
  for (const seg of segs) {
    if (seg.startsWith(":")) {
      let chosen = dynamicAt.get(parentKey);
      if (!chosen) {
        chosen = seg.slice(1);
        dynamicAt.set(parentKey, chosen);
      }
      const folder = "[" + chosen + "]";
      out.push(folder);
      parentKey = parentKey + "/" + folder;
    } else {
      out.push(seg);
      parentKey = parentKey + "/" + seg;
    }
  }
  return out;
}

// methods: Map(method -> originalExpressPath). Several original paths can share
// one Next folder when they differ only in a dynamic param name (e.g.
// /api/clients/:clientId/actions and /api/clients/:id/actions). Each method
// dispatches to the FIRST-registered original path, matching express first-match.
function fileContent(methods) {
  const METHOD_ORDER = ["GET", "POST", "PUT", "PATCH", "DELETE"];
  const entries = METHOD_ORDER.filter((m) => methods.has(m)).map((m) => [
    m,
    methods.get(m),
  ]);
  const routes = [...new Set(entries.map(([, p]) => p))].join(", ");
  const lines = [
    `// AUTO-GENERATED by scripts/gen-routes.mjs`,
    `// Route(s): ${routes}`,
    `// Forwards to the original Express handler in lib/server/app.js.`,
    `import { dispatch } from "@/lib/server/dispatch.js";`,
    ``,
    `export const runtime = "nodejs";`,
    `export const dynamic = "force-dynamic";`,
    ``,
  ];
  for (const [m, p] of entries) {
    lines.push(`export function ${m}(request) {`);
    lines.push(`  return dispatch("${m}", ${JSON.stringify(p)}, request);`);
    lines.push(`}`);
    lines.push(``);
  }
  return lines.join("\n");
}

// Group routes by destination folder, recording the first original path per
// method (express first-match semantics). nextSegments() is called for every
// route in registration order so dynamic-slug normalization stays consistent.
// Only the JSON API is still generated. Every other screen is a hand-written
// page under app/<route>/page.jsx, and a folder cannot hold both a page.jsx and
// a route.js — regenerating those would break the build.
const isApiRoute = (p) => p.startsWith("/api/") || p === "/api";

const byFolder = new Map(); // folderKey -> { segs, methods: Map(method -> path) }
for (const r of app.routes) {
  // nextSegments() still runs for every route so dynamic-slug naming stays
  // consistent with the folders that already exist.
  const segs = nextSegments(r.path);
  if (!isApiRoute(r.path)) continue;
  const key = segs.join("/");
  if (!byFolder.has(key)) byFolder.set(key, { segs, methods: new Map() });
  const folder = byFolder.get(key);
  if (!folder.methods.has(r.method)) folder.methods.set(r.method, r.path);
}

// Clean any previously generated route files (leave non-generated files alone).
function cleanGenerated(dir) {
  if (!fs.existsSync(dir)) return;
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      cleanGenerated(full);
      if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
    } else if (entry.name === "route.js") {
      const head = fs.readFileSync(full, "utf8").slice(0, 40);
      if (head.includes("AUTO-GENERATED")) fs.unlinkSync(full);
    }
  }
}

cleanGenerated(path.join(APP_DIR, "api"));
fs.mkdirSync(APP_DIR, { recursive: true });

let count = 0;
for (const { segs, methods } of byFolder.values()) {
  const dir = path.join(APP_DIR, ...segs);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "route.js"), fileContent(methods));
  count++;
}

console.log(
  `Generated ${count} API route files under app/api/ ` +
    `(from ${app.routes.length} registered routes; non-API routes are pages).`,
);
