// Emits app/globals.css from the CSS builders that used to be inlined into
// every rendered page's <style> tag by lib/server/app.js.
//
// Generating it rather than hand-copying keeps the React pages byte-identical
// to the HTML-string pages they replace: same custom properties, same base
// element styles, same top-nav and SweetAlert rules, in the same order every
// render*Page function composed them.
//
// Run with:  node scripts/gen-css.mjs

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import {
  buildThemeCss,
  buildBasePageCss,
  buildTopNavCss,
  buildSweetAlertCss,
  buildAutoReportCss,
} from "../lib/server/app.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.resolve(__dirname, "..", "app", "globals.css");

const banner = `/* AUTO-GENERATED by scripts/gen-css.mjs — do not edit by hand.
 *
 * Source of truth: buildThemeCss() / buildBasePageCss() / buildTopNavCss() /
 * buildSweetAlertCss() / buildAutoReportCss() in lib/server/app.js, concatenated in the order the
 * original render*Page functions composed them into each page's <style> tag.
 *
 * Page-specific CSS is NOT here — it lives beside each page as a CSS module.
 */
`;

const css = [
  banner,
  "/* ---- theme custom properties ---------------------------------------- */",
  buildThemeCss(),
  "/* ---- base page elements --------------------------------------------- */",
  buildBasePageCss(),
  "/* ---- top navigation -------------------------------------------------- */",
  buildTopNavCss(),
  "/* ---- SweetAlert-style dialogs ---------------------------------------- */",
  buildSweetAlertCss(),
  // Auto-report chart kit — shared by /clients/:id and /client-view/:token.
  buildAutoReportCss(),
].join("\n");

fs.writeFileSync(OUT, css, "utf8");
console.log(
  `Wrote ${path.relative(path.resolve(__dirname, ".."), OUT)} (${css.length} bytes)`,
);
