// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /api/team-work/columns/:id
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function DELETE(request) {
  return dispatch("DELETE", "/api/team-work/columns/:id", request);
}
