// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /api/lead-voice-uploads/bulk-delete
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function DELETE(request) {
  return dispatch("DELETE", "/api/lead-voice-uploads/bulk-delete", request);
}
