// AUTO-GENERATED by scripts/gen-routes.mjs
// Route(s): /clients/:id/reset
// Forwards to the original Express handler in lib/server/app.js.
import { dispatch } from "@/lib/server/dispatch.js";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export function GET(request) {
  return dispatch("GET", "/clients/:id/reset", request);
}

export function POST(request) {
  return dispatch("POST", "/clients/:id/reset", request);
}
